[package]
name = "noirplayground"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", rev = "f5921e0f7e69f474ee0a88b6ecfb52252fc7cc3d" }
starknet = "2.9.1"

[cairo]
sierra-replace-ids = false

[dev-dependencies]
cairo_test = "2.9.1"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
